package dev.fritze.skyward.core.astro

import dev.fritze.skyward.core.model.CometElements
import dev.fritze.skyward.core.model.CometMagParams
import dev.fritze.skyward.core.testing.Fixtures
import io.github.cosinekitty.astronomy.Vector
import io.github.cosinekitty.astronomy.rotationEclEqj
import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.acos
import kotlin.math.cos
import kotlin.math.log10
import kotlin.math.sin
import kotlin.math.sqrt
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue
import kotlin.time.Instant

/**
 * §17.3b's oracle: the universal-variable propagator (§7.4.2) against daily
 * JPL Horizons ephemerides, one year per comet, for the four comets §17.3b
 * names — 2P/Encke (short-period, e=0.85, q<0.5 au), C/2020 F3 NEOWISE
 * (near-parabolic, e=0.999), 2I/Borisov (hyperbolic, e=3.36) and
 * 96P/Machholz 1 (q=0.12 au).
 *
 * Every quantity §17.3b asks for is checked: heliocentric `r`, geocentric
 * `delta`, RA/Dec, and magnitude against Horizons' own T-mag. The fixtures
 * (`jpl_horizons_comet_elements.csv`, `jpl_horizons_comet_ephemerides.csv`,
 * regenerated by `tools/fixtures/fetch-horizons.py`) hold Horizons'
 * **geometric** positions — no light-time or aberration correction — because
 * that is what this propagator computes; comparing against Horizons'
 * astrometric RA/Dec would spend a fifth of the angular budget on a
 * correction that is not the propagator's job.
 *
 * The tolerances are tighter than §17.3b's, not looser: see the constants
 * at the bottom for the measured residuals, and
 * `docs/adr/0014-kepler-oracle-tolerances-tighter-than-spec-floor.md` for why
 * that's the right thing to assert instead of just the spec's own floor.
 * What makes it possible is where the elements come from. Propagating
 * today's osculating solution back across several apparitions accumulates
 * every perturbation the two-body model omits, which is why an earlier
 * version of this test needed a 5 % position tolerance; taking Horizons'
 * solution osculating **at each comet's perihelion** and checking it over
 * that perihelion ±182 days measures the propagator instead of measuring
 * how stale its inputs were.
 *
 * That is also the limit of what this file claims. It bounds the propagator
 * over half a year either side of an element epoch. It does not bound the
 * app's end-to-end comet accuracy, which depends on how old the SBDB
 * elements are and how far §7.4.3's scan reaches past them — §7.4.4's
 * honesty requirements exist for that, and the v1.1 backlog item
 * "non-gravitational terms in comet propagation" is where it would improve.
 *
 * The propagator's fixture-free properties (convergence across the full
 * eccentricity range, continuity through e=1) stay in `commonTest`'s
 * `KeplerTest`, which needs no captured data and so runs on every target.
 *
 * Ephemerides courtesy of the Jet Propulsion Laboratory, California
 * Institute of Technology.
 */
class KeplerHorizonsFixtureTest {

    @Test
    fun heliocentricDistanceMatchesHorizons() {
        forEachComet { comet, worst ->
            assertTrue(
                worst.rErrorAu <= R_TOLERANCE_AU,
                "${comet.name}: heliocentric r is off by ${"%.5f".format(worst.rErrorAu)} au at ${worst.rAt} " +
                    "(tolerance ${R_TOLERANCE_AU} au)",
            )
        }
    }

    @Test
    fun heliocentricPositionVectorMatchesHorizons() {
        // r alone is a scalar: a wrong rotation of the orbital plane leaves it
        // untouched. This is the assertion that catches a sign error in the
        // P/Q vectors or a swapped axis, and it is why the fixture carries
        // Horizons' heliocentric x/y/z rather than only the distance.
        forEachComet { comet, worst ->
            assertTrue(
                worst.positionErrorAu <= POSITION_TOLERANCE_AU,
                "${comet.name}: heliocentric position is off by ${"%.5f".format(worst.positionErrorAu)} au at " +
                    "${worst.positionAt} (tolerance ${POSITION_TOLERANCE_AU} au)",
            )
        }
    }

    @Test
    fun geocentricDistanceMatchesHorizons() {
        forEachComet { comet, worst ->
            assertTrue(
                worst.deltaErrorAu <= DELTA_TOLERANCE_AU,
                "${comet.name}: geocentric delta is off by ${"%.5f".format(worst.deltaErrorAu)} au at " +
                    "${worst.deltaAt} (tolerance ${DELTA_TOLERANCE_AU} au)",
            )
        }
    }

    @Test
    fun apparentDirectionMatchesHorizonsRaDec() {
        // §17.3b asks for RA/Dec within a tolerance; asserted as the angle
        // between the two unit vectors rather than as separate RA and Dec
        // deltas, because an RA difference means very different things at
        // Dec 0 and Dec 85 — 96P reaches Dec -80, where a degree of RA is
        // ten arcminutes on the sky. The angular separation is the quantity
        // an observer would actually be wrong by.
        //
        // This is also the one assertion that would catch §7.4.1's named
        // failure — "a missed JD/TDB unit conversion shows up as a wholesale
        // ephemeris offset rather than an error" — and the ecliptic-to-
        // equatorial rotation, which nothing tested against an oracle before.
        forEachComet { comet, worst ->
            assertTrue(
                worst.directionErrorDeg <= DIRECTION_TOLERANCE_DEG,
                "${comet.name}: apparent direction is off by ${"%.4f".format(worst.directionErrorDeg)}° at " +
                    "${worst.directionAt} (tolerance ${DIRECTION_TOLERANCE_DEG}°)",
            )
        }
    }

    @Test
    fun predictedMagnitudeMatchesHorizonsTotalMagnitude() {
        // Horizons computes T-mag as M1 + 5*log10(delta) + k1*log10(r) from
        // the same fitted M1/k1 the fixture carries, which is the formula
        // ADR 0004 settled on — so this is a geometry check expressed in
        // magnitudes, exactly as §17.3b says. It is a sharper geometry check
        // than it looks for the deep-perihelion comets: 96P's k1 of 8.75
        // turns a 1 % error in r into 0.038 mag.
        forEachComet { comet, worst ->
            assertTrue(
                worst.magnitudeError <= MAGNITUDE_TOLERANCE,
                "${comet.name}: predicted magnitude is off by ${"%.3f".format(worst.magnitudeError)} mag at " +
                    "${worst.magnitudeAt} (tolerance $MAGNITUDE_TOLERANCE mag)",
            )
        }
    }

    @Test
    fun theMagnitudeOracleIsOnlyEverSkippedWhereHorizonsContradictsItself() {
        // One row in 1460 is excluded from the check above: 96P on
        // 2017-10-26, where Horizons publishes a flat `6.0` while its own
        // r = 0.1542 au and delta = 0.8999 au with its own M1/k1 give 6.368.
        // Every other row agrees with that formula to 0.0025 mag or better,
        // so this is the oracle disagreeing with itself — most likely a
        // limit or a rounding in Horizons' own output for a comet this close
        // to the Sun — not the propagator being wrong. Excluding it is
        // legitimate; excluding it silently would not be, so the count is
        // pinned here: if a fixture regeneration produces more such rows,
        // that is a change in the oracle worth looking at before the
        // exclusions are widened.
        for (comet in fixtures()) {
            val skipped = comet.samples.filterNot { it.tmagAgreesWithHorizonsOwnGeometry(comet.magParams) }
            assertTrue(
                skipped.size <= 1,
                "${comet.name}: ${skipped.size} rows where Horizons' T-mag disagrees with its own r/delta " +
                    "(${skipped.map { it.time }}) — expected at most the known 96P row",
            )
        }
        val allSkipped = fixtures().flatMap { comet ->
            comet.samples.filterNot { it.tmagAgreesWithHorizonsOwnGeometry(comet.magParams) }.map { comet.key to it.time }
        }
        assertEquals(
            listOf("machholz" to Instant.parse("2017-10-26T00:00:00.000Z")),
            allSkipped,
            "the set of self-inconsistent oracle rows changed",
        )
    }

    @Test
    fun theOracleCoversTheYearAndTheRegimes17_3bAsksFor() {
        // A tolerance test passes trivially against an empty fixture, and
        // "one year, daily" is part of what §17.3b specifies — so assert the
        // shape of the oracle itself, not just the residuals.
        val comets = fixtures()
        assertTrue(comets.size == 4, "§17.3b names four comets, fixture has ${comets.map { it.name }}")

        val eccentricities = comets.map { it.elements.eccentricity }
        assertTrue(eccentricities.any { it in 0.5..0.95 }, "no short-period elliptical comet in $eccentricities")
        assertTrue(eccentricities.any { it in 0.99..1.0 }, "no near-parabolic comet in $eccentricities")
        assertTrue(eccentricities.any { it > 1.02 }, "no genuinely hyperbolic comet in $eccentricities")
        assertTrue(comets.any { it.elements.perihelionDistanceAu < 0.5 }, "no comet with perihelion inside 0.5 au")

        for (comet in comets) {
            assertTrue(comet.samples.size >= 360, "${comet.name}: ${comet.samples.size} samples, expected a daily year")
            val spanDays = (comet.samples.last().time - comet.samples.first().time).inWholeDays
            assertTrue(spanDays >= 360, "${comet.name}: fixture spans $spanDays days, expected a year")
            // Centred on perihelion, so the propagation is checked equally
            // far either side of the epoch its elements osculate at.
            val tp = comet.elements.tpPerihelion
            assertTrue(
                tp > comet.samples.first().time && tp < comet.samples.last().time,
                "${comet.name}: perihelion $tp is outside the sampled span",
            )
        }
    }

    @Test
    fun perihelionRadiusEqualsQAtTimeOfPerihelionPassage() {
        for (comet in fixtures()) {
            val pos = heliocentricPosition(comet.elements, comet.elements.tpPerihelion)
            assertNotNull(pos, "${comet.name}: expected convergence exactly at perihelion")
            assertTrue(
                abs(pos.length() - comet.elements.perihelionDistanceAu) < 1e-6,
                "${comet.name}: expected r == q (${comet.elements.perihelionDistanceAu}) at tp, got ${pos.length()}",
            )
        }
    }

    @Test
    fun apparentMagnitudeIsFiniteAndPlausibleNearPerihelion() {
        val mag = apparentMagnitude(encke.elements, ENCKE_MAG_PARAMS, encke.elements.tpPerihelion)
        assertNotNull(mag)
        // This broad range rejects non-finite values and gross magnitude
        // errors; it does not by itself distinguish a correct coefficient
        // from a subtly wrong one -- see the regression test below for that.
        assertTrue(mag in -5.0..25.0, "expected a plausible apparent magnitude, got $mag")
    }

    @Test
    fun apparentMagnitudeUsesTheDirectK1CoefficientNotMpcs2Point5nConvention() {
        // Regression for docs/adr/0004-comet-magnitude-formula.md: the broad
        // plausibility band above can't tell `m1 + K1*log10(r)` (correct, per
        // JPL SBDB) apart from the obsolete `m1 + 2.5*K1*log10(r)` this app
        // used to compute. `expected` is written out literally here -- not by
        // calling apparentMagnitude() -- so a regression to the 2.5x form
        // would change apparentMagnitude()'s output without changing this
        // expectation, and the test would fail.
        val t = encke.elements.tpPerihelion
        val elements = encke.elements

        // r == q exactly at perihelion passage (see
        // perihelionRadiusEqualsQAtTimeOfPerihelionPassage); delta comes from
        // the same position engine the fixtures above validate against
        // Horizons.
        val r = elements.perihelionDistanceAu
        val cometHelio = heliocentricPosition(elements, t)
        assertNotNull(cometHelio)
        val earthHelio = earthHeliocentricPositionEcliptic(t)
        val delta = (cometHelio - earthHelio).length()

        val expected = ENCKE_MAG_PARAMS.m1 + 5.0 * log10(delta) + ENCKE_MAG_PARAMS.k1 * log10(r)
        val actual = apparentMagnitude(elements, ENCKE_MAG_PARAMS, t)
        assertNotNull(actual)
        assertEquals(expected, actual, 1e-9)

        val obsoleteDoubleCountedForm = ENCKE_MAG_PARAMS.m1 + 5.0 * log10(delta) + 2.5 * ENCKE_MAG_PARAMS.k1 * log10(r)
        assertTrue(
            abs(obsoleteDoubleCountedForm - actual) > 1.0,
            "expected the corrected formula to differ meaningfully from the obsolete 2.5*K1 form",
        )
    }

    // ---- residuals ---------------------------------------------------------

    private val encke: CometFixture get() = fixtures().first { it.key == "encke" }

    private fun forEachComet(assertOn: (CometFixture, Worst) -> Unit) {
        for (comet in fixtures()) assertOn(comet, worstResiduals(comet))
    }

    private data class Worst(
        val rErrorAu: Double = 0.0, val rAt: Instant? = null,
        val positionErrorAu: Double = 0.0, val positionAt: Instant? = null,
        val deltaErrorAu: Double = 0.0, val deltaAt: Instant? = null,
        val directionErrorDeg: Double = 0.0, val directionAt: Instant? = null,
        val magnitudeError: Double = 0.0, val magnitudeAt: Instant? = null,
    )

    private fun worstResiduals(comet: CometFixture): Worst = residualsByComet.getValue(comet.key)

    private val residualsByComet: Map<String, Worst> by lazy {
        fixtures().associate { comet -> comet.key to computeResiduals(comet) }
    }

    private fun computeResiduals(comet: CometFixture): Worst {
        var worst = Worst()
        for (sample in comet.samples) {
            val computed = heliocentricPosition(comet.elements, sample.time)
            assertNotNull(computed, "${comet.name}: propagator failed to converge at ${sample.time}")

            val rError = abs(computed.length() - sample.rAu)
            if (rError > worst.rErrorAu) worst = worst.copy(rErrorAu = rError, rAt = sample.time)

            val positionError = (computed - sample.helio).length()
            if (positionError > worst.positionErrorAu) {
                worst = worst.copy(positionErrorAu = positionError, positionAt = sample.time)
            }

            val geocentric = computed - earthHeliocentricPositionEcliptic(sample.time)
            val deltaError = abs(geocentric.length() - sample.deltaAu)
            if (deltaError > worst.deltaErrorAu) worst = worst.copy(deltaErrorAu = deltaError, deltaAt = sample.time)

            val directionError = angleBetweenDeg(equatorialUnit(geocentric, sample.time), sample.direction)
            if (directionError > worst.directionErrorDeg) {
                worst = worst.copy(directionErrorDeg = directionError, directionAt = sample.time)
            }

            val magnitude = apparentMagnitude(comet.elements, comet.magParams, sample.time)
            assertNotNull(magnitude, "${comet.name}: no magnitude at ${sample.time}")
            if (sample.tmagAgreesWithHorizonsOwnGeometry(comet.magParams)) {
                val magnitudeError = abs(magnitude - sample.tmag)
                if (magnitudeError > worst.magnitudeError) {
                    worst = worst.copy(magnitudeError = magnitudeError, magnitudeAt = sample.time)
                }
            }
        }
        return worst
    }

    /** The propagator works in J2000 ecliptic; Horizons' RA/Dec are J2000 equatorial. */
    private fun equatorialUnit(eclipticGeocentric: Vec3, t: Instant): Vec3 {
        val v = eclipticGeocentric
        val rotated = rotationEclEqj().rotate(Vector(v.x, v.y, v.z, t.toAstroTime()))
        val length = sqrt(rotated.x * rotated.x + rotated.y * rotated.y + rotated.z * rotated.z)
        return Vec3(rotated.x / length, rotated.y / length, rotated.z / length)
    }

    private fun angleBetweenDeg(a: Vec3, b: Vec3): Double =
        acos((a.x * b.x + a.y * b.y + a.z * b.z).coerceIn(-1.0, 1.0)) * 180.0 / PI

    // ---- fixtures ----------------------------------------------------------

    private data class Sample(
        val time: Instant,
        val helio: Vec3,
        val rAu: Double,
        val deltaAu: Double,
        /** Unit vector in J2000 equatorial coordinates, from the published RA/Dec. */
        val direction: Vec3,
        val tmag: Double,
    ) {
        /**
         * Whether Horizons' published T-mag matches what its own r and delta
         * give through its own M1/k1. See
         * [theMagnitudeOracleIsOnlyEverSkippedWhereHorizonsContradictsItself].
         */
        fun tmagAgreesWithHorizonsOwnGeometry(mp: CometMagParams): Boolean =
            abs(tmag - (mp.m1 + 5.0 * log10(deltaAu) + mp.k1 * log10(rAu))) <= 0.01
    }

    private data class CometFixture(
        val key: String,
        val name: String,
        val elements: CometElements,
        val magParams: CometMagParams,
        val samples: List<Sample>,
    )

    private fun fixtures(): List<CometFixture> = cachedFixtures

    private val cachedFixtures: List<CometFixture> by lazy {
        val samplesByComet = Fixtures.csv("jpl_horizons_comet_ephemerides.csv")
            .groupBy({ it.getValue("comet") }) { row ->
                val ra = row.getValue("ra_deg").toDouble() * PI / 180.0
                val dec = row.getValue("dec_deg").toDouble() * PI / 180.0
                Sample(
                    time = Instant.parse(row.getValue("time_utc")),
                    helio = Vec3(
                        row.getValue("helio_x_au").toDouble(),
                        row.getValue("helio_y_au").toDouble(),
                        row.getValue("helio_z_au").toDouble(),
                    ),
                    rAu = row.getValue("r_au").toDouble(),
                    deltaAu = row.getValue("delta_au").toDouble(),
                    direction = Vec3(cos(dec) * cos(ra), cos(dec) * sin(ra), sin(dec)),
                    tmag = row.getValue("tmag").toDouble(),
                )
            }
            .mapValues { (_, samples) -> samples.sortedBy { it.time } }

        Fixtures.csv("jpl_horizons_comet_elements.csv").map { row ->
            val key = row.getValue("comet")
            val tpUtc = Instant.parse(row.getValue("tp_utc"))
            CometFixture(
                key = key,
                name = row.getValue("name"),
                elements = CometElements(
                    // The fixture's elements osculate at perihelion, so that is
                    // the epoch; the propagator itself only uses tpPerihelion.
                    epoch = tpUtc,
                    eccentricity = row.getValue("eccentricity").toDouble(),
                    perihelionDistanceAu = row.getValue("perihelion_distance_au").toDouble(),
                    inclinationDeg = row.getValue("inclination_deg").toDouble(),
                    ascendingNodeDeg = row.getValue("ascending_node_deg").toDouble(),
                    argPerihelionDeg = row.getValue("arg_perihelion_deg").toDouble(),
                    tpPerihelion = tpUtc,
                ),
                magParams = CometMagParams(m1 = row.getValue("m1").toDouble(), k1 = row.getValue("k1").toDouble()),
                samples = samplesByComet.getValue(key),
            )
        }
    }

    private companion object {
        // JPL SBDB's fitted M1/K1 for 2P/Encke as of this fixture's capture.
        // Not read from the fixture for the two magnitude-formula tests:
        // those are about the formula, and pinning the coefficients keeps a
        // refreshed fit from quietly moving the expectation the regression
        // test exists to hold still.
        val ENCKE_MAG_PARAMS = CometMagParams(m1 = 15.6, k1 = 4.5)

        // §17.3b's own figures are 0.001 au for r, 0.002 au for delta,
        // 0.05 deg for RA/Dec and 0.1 mag. Two-body propagation of a solution
        // osculating at perihelion beats all four across these four comets
        // and this whole year, by between 5x and 40x, so the ceilings below
        // are set at roughly twice the worst residual actually observed
        // rather than at the spec's numbers. They satisfy §17.3b a fortiori
        // and they are tight enough to be a regression net, which a bound
        // thirty times the real error would not be. Worst observed:
        //
        //   comet     r          position   delta      direction   magnitude
        //   Encke     1.4e-4 au  1.6e-4 au  1.5e-4 au  0.0011 deg  0.0011 mag
        //   NEOWISE   2.8e-5 au  6.4e-5 au  3.1e-5 au  0.0010 deg  0.0025 mag
        //   Borisov   1.8e-4 au  2.4e-4 au  1.8e-4 au  0.0016 deg  0.0011 mag
        //   96P       1.8e-5 au  7.7e-5 au  1.9e-5 au  0.0016 deg  0.0011 mag
        const val R_TOLERANCE_AU = 0.0005
        const val POSITION_TOLERANCE_AU = 0.0005
        const val DELTA_TOLERANCE_AU = 0.0005
        const val DIRECTION_TOLERANCE_DEG = 0.005
        const val MAGNITUDE_TOLERANCE = 0.01
    }
}
