package dev.fritze.skyward.ui.chart

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.graphics.Color
import dev.fritze.skyward.core.model.Phenomenon
import dev.fritze.skyward.core.model.Quality

/**
 * Fixed semantic colours for the drawn views (§14.1–§14.4), deliberately
 * outside Material You.
 *
 * §13 puts the Android app on dynamic colour, and every other screen
 * follows it — `ui/common/QualityColor.kt` resolves the quality ramp
 * against `MaterialTheme.colorScheme` precisely so it matches its
 * surroundings.
 *
 * A chart cannot. Dynamic colour derives a scheme from the user's
 * wallpaper, so on one device the aurora overlay would come out pink and
 * the eight phenomenon lanes on the timeline would collapse toward each
 * other. These hues carry meaning — green *is* the aurora, NOAA's G-scale
 * bands run green→red — and meaning cannot be reassigned per wallpaper.
 * See docs/adr/0024-charts-opt-out-of-dynamic-colour.md.
 *
 * The values mirror `:desktopApp`'s `SkywardPalette` so the same event is
 * the same colour on both, which is also why they are written out rather
 * than derived: two palettes generated by different rules would drift.
 */
object ChartPalette {

    @Composable
    @ReadOnlyComposable
    fun quality(quality: Quality): Color = pick(
        when (quality) {
            Quality.NONE -> 0xFF5A6377 to 0xFF4A5262
            Quality.MARGINAL -> 0xFFD8A657 to 0xFF8A5A00
            Quality.GOOD -> 0xFF6FB2E8 to 0xFF15558F
            Quality.EXCELLENT -> 0xFF6FE3A8 to 0xFF11694A
        },
    )

    /** Lane colours for the timeline (§14.2) and layer colours on the map (§14.1). */
    @Composable
    @ReadOnlyComposable
    fun phenomenon(phenomenon: Phenomenon): Color = pick(
        when (phenomenon) {
            Phenomenon.SOLAR_ECLIPSE -> 0xFFFFC65C to 0xFF8A6100
            Phenomenon.LUNAR_ECLIPSE -> 0xFFD08BE0 to 0xFF7B3E92
            Phenomenon.AURORA -> 0xFF5FE3B0 to 0xFF0F6B4F
            Phenomenon.METEOR_SHOWER -> 0xFF7FB4FF to 0xFF215394
            Phenomenon.COMET -> 0xFF9FE8E0 to 0xFF1C6E6B
            Phenomenon.MOON_EVENT -> 0xFFDCDCE6 to 0xFF5A5E6B
            Phenomenon.CONJUNCTION -> 0xFFF2907A to 0xFFA3462B
            Phenomenon.TERRESTRIAL -> 0xFFE0705F to 0xFFA32E1E
        },
    )

    /** §14.4's Kp classes, coloured by NOAA's own G-scale bands. */
    @Composable
    @ReadOnlyComposable
    fun kp(kp: Double): Color = pick(
        when {
            kp < 4.0 -> 0xFF4F8A5B to 0xFF2F6B3D
            kp < 5.0 -> 0xFFB7C24A to 0xFF66701A
            kp < 6.0 -> 0xFFE0B33C to 0xFF8A6200
            kp < 7.0 -> 0xFFE08A3C to 0xFF8F4C0F
            kp < 8.0 -> 0xFFE05C3C to 0xFF9E2F16
            else -> 0xFFD03A6B to 0xFF8C1244
        },
    )

    /** The ocean and land fills the map and mini-map are drawn over. */
    val Ocean = Color(0xFF0D1522)
    val LandFill = Color(0xFF243044)
    val LandStroke = Color(0xFF4A5B78)
    val Pin = Color(0xFFF2F5FA)

    @Composable
    @ReadOnlyComposable
    private fun pick(darkToLight: Pair<Long, Long>): Color =
        Color(if (LocalChartDarkTheme.current) darkToLight.first else darkToLight.second)
}

/**
 * Whether the charts should use their dark hues.
 *
 * Deliberately not `isSystemInDarkTheme()`: §11's `theme` setting can
 * override the OS (`ThemeChoice.LIGHT`/`DARK`), and a chart reading the
 * system value directly would contradict the surface it is drawn on the
 * moment a user sets that override. `SkywardTheme` provides the same
 * resolved `dark` it hands to Material.
 *
 * Defaults to dark for the same reason `SkywardTheme` does — a composable
 * rendered outside the theme (a preview, a test harness) should get the
 * palette the app usually runs in rather than one that silently disagrees.
 */
val LocalChartDarkTheme = staticCompositionLocalOf { true }

/** §14.4's G-scale label for a Kp value, or null below G1. */
fun gScaleLabel(kp: Double): String? = when {
    kp < 5.0 -> null
    kp < 6.0 -> "G1"
    kp < 7.0 -> "G2"
    kp < 8.0 -> "G3"
    kp < 9.0 -> "G4"
    else -> "G5"
}
