package dev.fritze.skyward.core.sources

import dev.fritze.skyward.core.astro.toAstroTime
import dev.fritze.skyward.core.astro.toInstant
import dev.fritze.skyward.core.model.GeoPoint
import dev.fritze.skyward.core.model.SolarEclipseKind
import dev.fritze.skyward.core.model.SolarEclipsePayload
import dev.fritze.skyward.core.model.TimeWindow
import dev.fritze.skyward.core.visibility.haversineDistanceKm
import io.github.cosinekitty.astronomy.EclipseKind
import io.github.cosinekitty.astronomy.Observer
import io.github.cosinekitty.astronomy.searchLocalSolarEclipse
import kotlinx.coroutines.runBlocking
import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.acos
import kotlin.math.asin
import kotlin.math.cos
import kotlin.math.sin
import kotlin.math.sqrt
import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertTrue
import kotlin.time.Duration
import kotlin.time.Duration.Companion.days
import kotlin.time.Duration.Companion.hours
import kotlin.time.Duration.Companion.minutes
import kotlin.time.Instant
import kotlin.time.measureTime

/**
 * §17.2's path-sampling tests, for all three §17.1 named eclipses, against
 * NASA/GSFC's published umbral-path tables.
 *
 * The fixture (`gsfc_central_paths_named_eclipses.csv`, regenerated by
 * `tools/fetch-gsfc-eclipse-paths.py`) is Espenak's own central line at the
 * published 120-second interval — the same canon §17.1's kind/peak/greatest
 * point sweeps use, not this app's computation reflected back at itself.
 * Eclipse predictions courtesy of Fred Espenak and Jean Meeus, NASA/GSFC.
 */
class EclipsePathCanonTest {

    @Test
    fun everyPathSampleIsIndependentlyATotalEclipsePoint() {
        // §17.2: "every PathSample.point must itself evaluate as TOTAL via
        // local search (self-consistency)". Deliberately an *independent*
        // re-evaluation rather than a read of the sample's own
        // centralDurationSec: the payload field comes from the same
        // LocalSolarEclipseInfo the sampler already had, so checking it
        // proves only that the sampler copied a number it was holding.
        for ((date, payload) in payloads()) {
            for (sample in payload.centralPath) {
                val local = searchLocalSolarEclipse(
                    (sample.time - 4.hours).toAstroTime(),
                    Observer(sample.point.latDeg, sample.point.lonDeg, 0.0),
                )
                val where = "$date ${sample.time} ${sample.point}"
                assertTrue(
                    local.kind == EclipseKind.Total,
                    "$where: independent local search says ${local.kind}, not TOTAL",
                )
                assertNotNull(local.totalBegin, "$where: no totality phase")
                assertNotNull(local.totalEnd, "$where: no totality phase")
                // And it must be *this* moment of the track, not some other
                // eclipse the search wandered onto.
                val peakDelta = abs((local.peak.time.toInstant() - sample.time).inWholeSeconds)
                assertTrue(
                    peakDelta <= 2.minutes.inWholeSeconds,
                    "$where: local peak is ${peakDelta}s from the sample's own time",
                )
            }
        }
    }

    @Test
    fun thePathPassesWithin50KmOfEveryPublishedCentrelinePoint() {
        // §17.2's centreline tolerance, at the spec's own 50 km. Measured to
        // the sampled *polyline*, not to the nearest sample: the app emits
        // one point per 2-minute bucket, so a nearest-sample metric would be
        // dominated by along-track granularity (a hundred km or more of
        // shadow travel) and would say nothing about whether the track is in
        // the right place. Point-to-polyline is what "the path passes within
        // 50 km of" means.
        for ((date, payload) in payloads()) {
            val polyline = payload.centralPath.map { it.point }
            val span = payload.centralPath.first().time..payload.centralPath.last().time
            // Published rows outside the sampled span have no segment to be
            // near; the span itself is asserted below.
            val published = centreline.getValue(date).filter { it.time in span }
            assertTrue(published.size >= 40, "$date: only ${published.size} published rows inside the sampled span")

            for (row in published) {
                val distanceKm = distanceToPolylineKm(row.point, polyline)
                assertTrue(
                    distanceKm <= 50.0,
                    "$date ${row.time}: published centreline point ${row.point} is " +
                        "${"%.1f".format(distanceKm)} km from the sampled path",
                )
            }
        }
    }

    @Test
    fun theSampledSpanCoversTheWholePublishedTrack() {
        // The companion to the tolerance above: staying within 50 km of the
        // published points you did cover is easy if you covered a third of
        // the track. The published table's own ends are the goal posts.
        for ((date, payload) in payloads()) {
            val published = centreline.getValue(date)
            val first = payload.centralPath.first().time
            val last = payload.centralPath.last().time
            assertTrue(
                first <= published.first().time + 2.minutes,
                "$date: sampling starts at $first, ${published.first().time} is already published",
            )
            assertTrue(
                last >= published.last().time - 2.minutes,
                "$date: sampling ends at $last, ${published.last().time} is still published",
            )
        }
    }

    @Test
    fun consecutiveSamplesStayWithinTheSpacingTheShadowAllows() {
        // §17.2 asks for < 400 km between consecutive samples. See
        // docs/adr/0009-eclipse-path-sample-spacing.md: that cannot hold as a
        // ceiling at §7.1.3's 2-minute bucketing, because NASA's own
        // 120-second table exceeds it on all three of these eclipses (up to
        // 818 km) where the shadow races along the terminator. It is asserted
        // here as the typical case, with a ceiling of one dropped bucket at
        // the fastest ground speed these paths reach.
        for ((date, payload) in payloads()) {
            val gaps = payload.centralPath.map { it.point }.zipWithNext()
                .map { (a, b) -> haversineDistanceKm(a, b) }
                .sorted()
            val median = gaps[gaps.size / 2]

            assertTrue(median < 400.0, "$date: median sample spacing ${"%.0f".format(median)} km (§17.2 wants < 400)")
            assertTrue(
                gaps.last() < 1500.0,
                "$date: worst sample spacing ${"%.0f".format(gaps.last())} km — see ADR 0009 for the 1500 km ceiling",
            )
        }
    }

    @Test
    fun theLongestTotalityOnThePathMatchesThePublishedMaximum() {
        // §17.1's totality-duration spot-checks, at the path level. The
        // published maximum is a 120-second sample of a continuous function,
        // so the true maximum is a little higher and the app — which
        // hill-climbs for it — should land just above, never below.
        for ((date, payload) in payloads()) {
            val computed = payload.centralPath.mapNotNull { it.centralDurationSec }.max()
            val published = centreline.getValue(date).maxOf { it.durationSec }
            assertTrue(
                computed >= published - 2.0,
                "$date: longest sampled totality ${computed}s is below the published ${published}s",
            )
            assertTrue(
                computed <= published + 10.0,
                "$date: longest sampled totality ${computed}s exceeds the published ${published}s by more than the " +
                    "sampling interval can explain",
            )
        }
    }

    @Test
    fun pathSamplingStaysWithinItsRuntimeBudget() {
        // §17.2/§18 M1: "< 60 s per eclipse on CI", now for all three rather
        // than 2026 alone — a cost regression that only shows on the longest
        // path (2027 traces a third of the globe) would otherwise go unseen.
        // Timed as the shared payloads are computed, so the budget covers a
        // real cold refresh without this case paying for three more.
        for ((date, elapsed) in samplingTimes()) {
            assertTrue(elapsed.inWholeSeconds < 60, "$date: path sampling took $elapsed, expected < 60 s")
        }
    }

    // ---- fixture + geometry ------------------------------------------------

    private data class CentrelineRow(val time: Instant, val point: GeoPoint, val durationSec: Double)

    /**
     * Point-to-polyline great-circle distance. Computed on the unit sphere
     * rather than in a flat projection because two of these paths run past
     * 80° latitude, where a degrees-times-cos approximation is worth tens of
     * km — the same order as the tolerance being asserted.
     */
    private fun distanceToPolylineKm(point: GeoPoint, polyline: List<GeoPoint>): Double =
        polyline.zipWithNext().minOf { (a, b) -> distanceToSegmentKm(point, a, b) }

    private fun distanceToSegmentKm(point: GeoPoint, start: GeoPoint, end: GeoPoint): Double {
        val p = unitVector(point)
        val a = unitVector(start)
        val b = unitVector(end)

        val normal = cross(a, b)
        val normalLength = length(normal)
        // Degenerate segment (repeated point): fall back to the endpoint.
        if (normalLength < 1e-12) return EARTH_RADIUS_KM * angleBetween(p, a)
        val unitNormal = normal.map { it / normalLength }

        // Signed angle off the great circle through a and b.
        val crossTrack = asin(dot(p, unitNormal).coerceIn(-1.0, 1.0))
        // Where p lands when dropped onto that great circle.
        val projected = normalize(p.mapIndexed { i, v -> v - sin(crossTrack) * unitNormal[i] })
        val arc = angleBetween(a, b)
        val fallsInsideSegment = angleBetween(a, projected) + angleBetween(projected, b) <= arc + 1e-9

        return if (fallsInsideSegment) {
            EARTH_RADIUS_KM * abs(crossTrack)
        } else {
            minOf(EARTH_RADIUS_KM * angleBetween(p, a), EARTH_RADIUS_KM * angleBetween(p, b))
        }
    }

    private fun unitVector(p: GeoPoint): List<Double> {
        val lat = p.latDeg * PI / 180.0
        val lon = p.lonDeg * PI / 180.0
        return listOf(cos(lat) * cos(lon), cos(lat) * sin(lon), sin(lat))
    }

    private fun dot(a: List<Double>, b: List<Double>) = a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
    private fun cross(a: List<Double>, b: List<Double>) = listOf(
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )

    private fun length(a: List<Double>) = sqrt(dot(a, a))
    private fun normalize(a: List<Double>) = length(a).let { l -> if (l == 0.0) a else a.map { it / l } }
    private fun angleBetween(a: List<Double>, b: List<Double>) = acos(dot(a, b).coerceIn(-1.0, 1.0))

    private companion object {
        const val EARTH_RADIUS_KM = 6371.0

        /** §17.1's three named eclipses, mapped to the app's own occurrence ids. */
        val ECLIPSES = mapOf(
            "2026-08-12" to "se:20260812",
            "2027-08-02" to "se:20270802",
            "2028-07-22" to "se:20280722",
        )

        /**
         * Each `refresh` runs full §7.1.3 path sampling, which is the most
         * expensive thing in this module's test suite — so the three payloads
         * are computed once for the class and shared by every case except the
         * runtime-budget one, which times a fresh call on purpose.
         */
        private val cachedPayloads: Map<String, Pair<SolarEclipsePayload, Duration>> by lazy {
            runBlocking {
                ECLIPSES.keys.associateWith { date ->
                    var payload: SolarEclipsePayload? = null
                    val elapsed = measureTime { payload = fetchPayload(date) }
                    payload!! to elapsed
                }
            }
        }

        fun payloads(): Map<String, SolarEclipsePayload> = cachedPayloads.mapValues { it.value.first }

        fun samplingTimes(): Map<String, Duration> = cachedPayloads.mapValues { it.value.second }

        suspend fun fetchPayload(date: String): SolarEclipsePayload {
            // A window around the eclipse day rather than the whole month:
            // every total or annular eclipse inside the horizon gets sampled,
            // so a wider window is paid for in full.
            val midnight = Instant.parse("${date}T00:00:00Z")
            val start = midnight - 2.days
            val end = midnight + 2.days
            val result = EclipseSource().refresh(
                RefreshRequest(
                    now = start,
                    horizon = TimeWindow(start, end),
                    locations = emptyList(),
                    state = emptyMap(),
                    settings = SourceSettings(),
                    derivedThresholds = DerivedThresholds(null, null, null),
                ),
            )
            val occurrence = result.occurrences.first { it.id == ECLIPSES.getValue(date) }
            val payload = occurrence.payload as SolarEclipsePayload
            check(payload.kind == SolarEclipseKind.TOTAL) { "$date should be a total eclipse, got ${payload.kind}" }
            check(payload.centralPath.isNotEmpty()) { "$date produced no central path" }
            return payload
        }

        val centreline: Map<String, List<CentrelineRow>> by lazy {
            val stream = checkNotNull(
                EclipsePathCanonTest::class.java.classLoader
                    .getResourceAsStream("fixtures/gsfc_central_paths_named_eclipses.csv"),
            ) { "missing fixture resource: fixtures/gsfc_central_paths_named_eclipses.csv" }
            val lines = stream.bufferedReader(Charsets.UTF_8).use { it.readText() }
                .lineSequence()
                .map { it.trim() }
                .filter { it.isNotEmpty() && !it.startsWith("#") }
                .toList()
            val header = lines.first().split(',')
            lines.drop(1)
                .map { header.zip(it.split(',')).toMap() }
                .groupBy({ it.getValue("eclipse_date") }) { row ->
                    CentrelineRow(
                        time = Instant.parse(row.getValue("time_utc")),
                        point = GeoPoint(
                            row.getValue("centre_lat_deg").toDouble(),
                            row.getValue("centre_lon_deg").toDouble(),
                        ),
                        durationSec = row.getValue("central_duration_sec").toDouble(),
                    )
                }
                .mapValues { (_, rows) -> rows.sortedBy { it.time } }
        }
    }
}
